version: '2'
services:

#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#  
#  rabbitmq:
#    image: rabbitmq:3.5.3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#     
#  mongodb:
#    image: mongo:3.0.4
#    ports:
#      - "27017:27017"
#    command: mongod --smallfiles
#    


## TOOLBOX

  ds-toolbox-apigateway-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./toolbox-modules/apigateway-service/target:/app
      - ./scripts:/scripts
    command: /scripts/wait-for-it.sh -t 30 -s ds-toolbox-discovery-service:8080 -- /scripts/run-spring-boot.sh /app/apigateway-service.jar
    environment:
      eureka.client.serviceUrl.defaultZone: http://ds-toolbox-discovery-service:8080/eureka
    ports:
      - "8000:8080"
      - "8100:3333"
    depends_on:
      - ds-toolbox-discovery-service

  ds-toolbox-discovery-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./toolbox-modules/discovery-service/target:/app
    command: java -jar -Xmx64m -Xss256k /app/discovery-service.jar
    ports:
      - "8001:8080"
      - "8101:3333"
## BACKEND

  ds-backend-catalog-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./backend-modules/catalog-service/target:/app
      - ./scripts:/scripts
    command: /scripts/wait-for-it.sh -t 30 -s ds-toolbox-discovery-service:8080 -- /scripts/run-spring-boot.sh /app/catalog-service.jar
    environment:
      eureka.client.serviceUrl.defaultZone: http://ds-toolbox-discovery-service:8080/eureka
    ports:
      - "9000:8080"
      - "9100:3333"
    depends_on:
      - ds-toolbox-discovery-service
      
  ds-backend-customers-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./backend-modules/customers-service/target:/app
      - ./scripts:/scripts
    command: /scripts/wait-for-it.sh -t 30 -s ds-toolbox-discovery-service:8080 -- /scripts/run-spring-boot.sh /app/customers-service.jar
    environment:
      eureka.client.serviceUrl.defaultZone: http://ds-toolbox-discovery-service:8080/eureka
    ports:
      - "9001:8080"
      - "9101:3333"
    depends_on:
      - ds-toolbox-discovery-service
      
  ds-backend-checkout-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./backend-modules/checkout-service/target:/app
      - ./scripts:/scripts
    command: /scripts/wait-for-it.sh -t 30 -s ds-toolbox-discovery-service:8080 -- /scripts/run-spring-boot.sh /app/checkout-service.jar
    environment:
      eureka.client.serviceUrl.defaultZone: http://ds-toolbox-discovery-service:8080/eureka
    ports:
      - "9002:8080"
      - "9102:3333"
    depends_on:
      - ds-toolbox-discovery-service
      - ds-backend-catalog-service

  ds-backend-search-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./backend-modules/search-service/target:/app
      - ./scripts:/scripts
    command: /scripts/wait-for-it.sh -t 30 -s ds-toolbox-discovery-service:8080 -- /scripts/run-spring-boot.sh /app/search-service.jar
    environment:
      eureka.client.serviceUrl.defaultZone: http://ds-toolbox-discovery-service:8080/eureka
    ports:
      - "9003:8080"
      - "9103:3333"
    depends_on:
      - ds-toolbox-discovery-service