version: '2'
services:

  datadog:
    image: datadog/docker-dd-agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/mounts:/host/proc/mounts:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8125:8125"
    environment:
      API_KEY: ${DDAK}

    privileged: true

#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#  
  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
#     
#  mongodb:
#    image: mongo:3.0.4
#    ports:
#      - "27017:27017"
#    command: mongod --smallfiles
#    


## TOOLBOX

  ds-toolbox-apigateway-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./toolbox-modules/apigateway-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/wait-for-config-and-discovery.sh /scripts/run-spring-boot.sh 128 apigateway-service.jar apigateway-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://ds-toolbox-config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "8000:8080"
    depends_on:
      - ds-toolbox-config-service
      - ds-toolbox-discovery-service
      - rabbitmq

  ds-toolbox-discovery-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./toolbox-modules/discovery-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/wait-for-it.sh -t 60 -s ds-toolbox-config-service:8080 -- /scripts/run-spring-boot.sh 90 discovery-service.jar discovery-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://ds-toolbox-config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
      METRICS_REPORTERS_TRANSPORT_APIKEY: ${DDAK}
    ports:
      - "8001:8080"
    depends_on:
      - ds-toolbox-config-service

  ds-toolbox-circuitmonitor-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./toolbox-modules/circuitmonitor-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/wait-for-config-and-discovery.sh /scripts/run-spring-boot.sh 90 circuitmonitor-service.jar circuitmonitor-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://ds-toolbox-config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "8002:8080"
      - "8989:8989"
    depends_on:
      - ds-toolbox-config-service
      - ds-toolbox-discovery-service
      - rabbitmq

  ds-toolbox-instancesadmin-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./toolbox-modules/instancesadmin-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/wait-for-config-and-discovery.sh /scripts/run-spring-boot.sh 90 instancesadmin-service.jar instancesadmin-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://ds-toolbox-config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "8003:8080"
    depends_on:
      - ds-toolbox-config-service
      - ds-toolbox-discovery-service

  ds-toolbox-config-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./toolbox-modules/config-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
      - ./configs:/configs
    command: /scripts/run-spring-boot.sh 90 config-service.jar config-service.yml
    environment:
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "8004:8080"

## BACKEND

  ds-backend-catalog-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./backend-modules/catalog-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/wait-for-config-and-discovery.sh /scripts/run-spring-boot.sh 90 catalog-service.jar catalog-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://ds-toolbox-config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "9000:8080"
    depends_on:
      - ds-toolbox-config-service
      - ds-toolbox-discovery-service

  ds-backend-customers-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./backend-modules/customers-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/wait-for-config-and-discovery.sh /scripts/run-spring-boot.sh 90 customers-service.jar customers-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://ds-toolbox-config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "9001:8080"
    depends_on:
      - ds-toolbox-config-service
      - ds-toolbox-discovery-service

  ds-backend-checkout-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./backend-modules/checkout-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/wait-for-config-and-discovery.sh /scripts/run-spring-boot.sh 128 checkout-service.jar checkout-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://ds-toolbox-config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "9002:8080"
    depends_on:
      - ds-toolbox-config-service
      - ds-toolbox-discovery-service
      - ds-backend-catalog-service
      - ds-backend-customers-service
      - rabbitmq

  ds-backend-search-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./backend-modules/search-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/wait-for-config-and-discovery.sh /scripts/run-spring-boot.sh 90 search-service.jar search-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://ds-toolbox-config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "9003:8080"
    depends_on:
      - ds-toolbox-config-service
      - ds-toolbox-discovery-service

  ds-backend-orders-service:
    image: java:openjdk-8u91-jdk
    working_dir: /app
    volumes:
      - ./backend-modules/orders-service/target:/app
      - ./scripts:/scripts
      - ./newrelic:/newrelic
    command: /scripts/wait-for-config-and-discovery.sh /scripts/run-spring-boot.sh 90 orders-service.jar orders-service.yml
    environment:
      SPRING_CLOUD_CONFIG_URI: http://ds-toolbox-config-service:8080
      SPRING_PROFILES_ACTIVE: docker-compose
      NEW_RELIC_LICENSE_KEY: ${NRLK}
    ports:
      - "9004:8080"
    depends_on:
      - ds-toolbox-config-service
      - ds-toolbox-discovery-service
      - rabbitmq