spring:
  profiles: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
---
spring:
  profiles: docker-compose

eureka:
  client:
    serviceUrl:
      defaultZone: http://ds-toolbox-discovery-service:8080/eureka/
